# Generated by Django 6.0.2 on 2026-04-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0003_company_alter_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
      
    ]
