# Generated by Django 6.0.3 on 2026-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_cashbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
