# Generated by Django 6.0.3 on 2026-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_cashbox_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
