# Generated by Django 6.0.3 on 2026-04-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
    ]
