# Generated by Django 6.0.3 on 2026-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_unit_company_unit_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
