# Generated by Django 6.0.3 on 2026-03-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.AddField(
            model_name='product',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
