# Generated by Django 6.0.2 on 2026-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
